#!/bin/bash

# This script is used to allow public accesss

aws s3api put-public-access-block \
  --bucket techcrush-project-26697 \
  --public-access-block-configuration BlockPublicAcls=false,IgnorePublicAcls=false,BlockPublicPolicy=false,RestrictPublicBuckets=false

aws s3api put-bucket-policy \
  --bucket techcrush-project-26697 \
  --policy '{
    "Version": "2012-10-17",
    "Statement": [
      {
        "Sid": "AllowPublicRead",
        "Effect": "Allow",
        "Principal": "*",
        "Action": "s3:GetObject",
        "Resource": "arn:aws:s3:::techcrush-project-26697/*"
      }
    ]
  }'
